### ISSUE TITLE
openhab 2 driver not connecting

### ISSUE THREAD

**Issue by rene54321** [Martin-Gleiss/smartvisu#110]
Hi,

I have installed smarvisu 2.8 on my nas. Openhab 2 is running on an RPI3. I have entered the IP of the openhab server and the standard openhab port ( 8080 ) the connection is not working. Do I need to do something else in openhab 2 or smartvisu to get this working.

regards René

**Comment by i-am-offline** [comment]
Is your openhab server accessible from the **client**? In smartvisu the connection to the backend is made by the client and not by the smartvisu server.

**Comment by rene54321** [comment]
Hi,

So it is not possible to install the smartvisu on an different device. So it has to be installed on the RPi were openhab2 is running? Both devices are in the same LAN and reachable by eachother.

Regards René

**Comment by i-am-offline** [comment]
It is possible to install smartvisu and openhab2 on different devices.  However, the client has to be able to reach both smartvisu **and** openhab2. The client gets the smartvisu webpage from the smartvisu device. He also gets the information on how to contact the openhab2 backend. Then the client establishes a connection with the backend.

**Comment by rene54321** [comment]
Yes the client itself is an PC and is able to reach both devices. Openhab2 shows following failure in the log:

2016-10-16 10:23:23.324 [ERROR] [ersey.server.ServerRuntime$Responder] - An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
 at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
 at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
 at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
 at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
 at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
 at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
 at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
 at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
 at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
 at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
 at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
 at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
 at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
 at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
 at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
 at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[11:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
 at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[77:org.eclipse.jetty.security:9.2.14.v20151106]
 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.eclipse.jetty.server.Server.handle(Server.java:499)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[78:org.eclipse.jetty.server:9.2.14.v20151106]
 at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[81:org.eclipse.jetty.util:9.2.14.v20151106]
 at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[81:org.eclipse.jetty.util:9.2.14.v20151106]
 at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: org.eclipse.jetty.io.EofException
 at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:364)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 at org.eclipse.jetty.io.SelectChannelEndPoint.onSelected(SelectChannelEndPoint.java:111)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:640)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:611)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:549)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)[81:org.eclipse.jetty.util:9.2.14.v20151106]
 ... 3 more
Caused by: java.io.IOException: DatenÃ¼bergabe unterbrochen (broken pipe)
 at sun.nio.ch.FileDispatcherImpl.write0(Native Method)[:1.8.0_101]
 at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)[:1.8.0_101]
 at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)[:1.8.0_101]
 at sun.nio.ch.IOUtil.write(IOUtil.java:65)[:1.8.0_101]
 at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)[:1.8.0_101]
 at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)[70:org.eclipse.jetty.io:9.2.14.v20151106]
 ... 10 more

**Comment by rene54321** [comment]
I am using latest beta 4 of openhab 2.

**Comment by rene54321** [comment]
Any idea?

**Comment by rene54321** [comment]
Hi,

could someboday give an short howto how the openhab2 config has to be done. With one openhab item and the smartvisu configuration for it. Short overview what I have tried until now:

- smartvisu config -> openhab2 ->ip op oh2 server -> port 8080 -> realtime and reconnect yes
-  created draft room menu page with one switch -> {{ basic.switch('switch1', 'Licht_Switch_SZ_Iris') }}
- The openhab2 two item config is -> Switch Licht_Switch_SZ_Iris     "Iris"      <light> 

Is something else needed to get this working?

regards René

**Comment by rene54321** [comment]
Hi,

problem solved see following thread for details:

https://knx-user-forum.de/forum/supportforen/smartvisu/1003345-smartvisu-2-8-openhab2-driver-probleme?p=1016738#post1016738
