### ISSUE TITLE
Uzsugraph bug when selecting first entry in graph

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#933]
When showing the graph starting with the current day, the last value of the previous day is also shown (on the very left, need to scroll). This is fine so far because otherwise of course the beginning of the current date would be shown wrong. However...
When selecting the very first data point in an uzsu graph (e.g. with cubic interpolation) alle subsequent selected points show an empty value and I receive this error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at $.<computed>.<computed>._uzsuFillTableRow (device.js:663:22)
    at $.isFunction.proxiedPrototype.<computed> [as _uzsuFillTableRow] (jquery.mobile-1.4.5-patch.min.js:1:12416)
    at $.<computed>.<computed>._uzsuRuntimePopup (device.js:2357:10)
    at $.isFunction.proxiedPrototype.<computed> [as _uzsuRuntimePopup] (jquery.mobile-1.4.5-patch.min.js:1:12416)
    at g.click (device.js:1907:22)
    at highstock.src.js:1639:25
    at Array.forEach (<anonymous>)
    at n (highstock.src.js:1636:17)
    at g.firePointEvent (highstock.src.js:24671:17)
    at a.onContainerClick (highstock.src.js:26405:29)
```
After reloading the page I can select all points (except first) without any issues. It's ok that the first point is not selectable as it is from the previous days.. but it somehow breaks any further point selection.

There is also one more minor issue: As there is only 1 value of the previous day shown, the cubic interpolation of (beginning of) "today" is not visualized correctly. The curve leaves the first "point" quite straight although that might differ depending on previous points.

**Comment by wvhn** [comment]
thanks for the hint. The bug also happens at the very last point in the graph (both points are added for better readability of the graph).

The bug is fixed with #934. I leave the issue open until I have checked whether an improvement of the cubic interpolation in the graph is possible.

**Comment by onkelandy** [comment]
Thanks for the quick fix, works like a charm.

**Comment by wvhn** [comment]
spline display improved with #950
